### PR TITLE
Issue #24 - Don't override XDG_DATA_DIRS

### LINKED ISSUE #24: Flatpak installed applications do not appear in the menu
Tracking down this issue, I found the root cause to be that startlxde-pi overrides any set XDG_DATA_DIRS, removing the additions that /etc/X11/Xsession.d/20flatpak adds. 

This change simply keeps any existing XDG_DATA_DIRS, prepending the FKMS directory if needed, and allows the searching of the user-specific Flatpak directories.

### LINKED ISSUE #28: startlxde-pi ovveride XDG_DATA_DIRS
`startlxde-pi` ovverides `XDG_DATA_DIRS` making any previous value gone.
(the problem is also in upstream `startlxde` in debian but it's not the one used on RaspberryPi OS)

This cause application installed using Flatpak to not be available in the menu.

Source:
https://www.raspberrypi.org/forums/viewtopic.php?t=275001
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=906288

Modifying startlxde-pi to NOT clobber `XDG_DATA_DIRS` fixes the problem.

### PR DESCRIPTION
**Pull request by hfiguiere**
This replaces #23 as I address this comment https://github.com/RPi-Distro/raspberrypi-ui-mods/pull/23#issuecomment-631464345

Let me know if you have question or feedback. I'd love to get this fixed so Flatpak can work better out of the box on Raspberry Pi OS.

Close #23 
Close #24 
Close #28 (dupe of #23)

### CODE REVIEW

**Comment by XECDesign** [comment]
@spl237 this doesn't seem to have any effect in cases where XDG_DATA_DIRS is initially unset (our default), so it should be fine.

**Comment by hfiguiere** [comment]
What do I need to do so this can get merged? This issue really breaks standard features.

**Comment by hfiguiere** [comment]
I rebased this PR. (and re-tested)

@spl237 what do I need to do to get this landed?

**Comment by spl237** [comment]
It'll be in the next release, probably sometime in August.

**Comment by hfiguiere** [comment]
Thanks !

**Pull request merged**
